# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_replicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='db_replicator.proto',
  package='db_replicator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x64\x62_replicator.proto\x12\rdb_replicator\"\x16\n\x06Sender\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2O\n\rDB_Replicator\x12>\n\x08Receiver\x12\x15.db_replicator.Sender\x1a\x17.db_replicator.Response\"\x00(\x01\x62\x06proto3'
)




_SENDER = _descriptor.Descriptor(
  name='Sender',
  full_name='db_replicator.Sender',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='db_replicator.Sender.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=60,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='db_replicator.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='db_replicator.Response.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Sender'] = _SENDER
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sender = _reflection.GeneratedProtocolMessageType('Sender', (_message.Message,), {
  'DESCRIPTOR' : _SENDER,
  '__module__' : 'db_replicator_pb2'
  # @@protoc_insertion_point(class_scope:db_replicator.Sender)
  })
_sym_db.RegisterMessage(Sender)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'db_replicator_pb2'
  # @@protoc_insertion_point(class_scope:db_replicator.Response)
  })
_sym_db.RegisterMessage(Response)



_DB_REPLICATOR = _descriptor.ServiceDescriptor(
  name='DB_Replicator',
  full_name='db_replicator.DB_Replicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=92,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='Receiver',
    full_name='db_replicator.DB_Replicator.Receiver',
    index=0,
    containing_service=None,
    input_type=_SENDER,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DB_REPLICATOR)

DESCRIPTOR.services_by_name['DB_Replicator'] = _DB_REPLICATOR

# @@protoc_insertion_point(module_scope)
