# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import db_replicator_pb2 as db__replicator__pb2


class DB_ReplicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Receiver = channel.stream_unary(
                '/db_replicator.DB_Replicator/Receiver',
                request_serializer=db__replicator__pb2.Sender.SerializeToString,
                response_deserializer=db__replicator__pb2.Response.FromString,
                )


class DB_ReplicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Receiver(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DB_ReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Receiver': grpc.stream_unary_rpc_method_handler(
                    servicer.Receiver,
                    request_deserializer=db__replicator__pb2.Sender.FromString,
                    response_serializer=db__replicator__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'db_replicator.DB_Replicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DB_Replicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Receiver(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/db_replicator.DB_Replicator/Receiver',
            db__replicator__pb2.Sender.SerializeToString,
            db__replicator__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
